name: golangci-lint
on:
  push:
    branches:
      - main
      - develop
      - personal/**
      - feature/**
      - enhance/**
      - fix/**
  pull_request:
    branches:
      - main
      - develop
      - personal/**
      - feature/**
      - enhance/**
      - fix/**

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read


jobs:
  golangci:
    name: golangci-lint
    strategy:
      matrix:
        go-version: [ 1.18.x,1.19.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3

      - name: Build Binary
        run: |
          echo "Building linux amd64 binary..."
          cd demo/todo
          GOOS=linux GOARCH=amd64 go build main.go
          chmod +x main
          ./main install -y

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          args: --timeout 3m0s